language: node_js
node_js:
    - '0.10'
    - '0.12'
branches:
    only:
        - master
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_script:
    - export DISPLAY=:99.0

services:
    - xvfb

script:
    - make test
    - make quality
deploy:
    provider: npm
    email: oscm@edx.org
    api_key:
      secure: b8cV3TIUNhQ8D3Ij0juCQP44E+4puR+wGcc6CO91AmTHxWqFZrfUGbweOM1K7Ipukq0jQkoGSBDsFTHBcHdy7e5+/rKR5vuMIE1K3T0V0Z5o3PA+i0v/YgEtmpTgJEu84uSQsNBojJdnWOhaGRSYcB/hG3Yw6NNT0ne3W531PYSne94usgmKheyUSBt9p0LjB4nurCNdwWRJ3gbEg2ljGjNCRNM0HxaLc3SEV6CflbUhZ88yuOmHfd+5XEBGhxwXoRnWqOGa+/Krf0mSNaKes4ibGOgboQWqfVEn0SGt5rxoxxtLsjVwvQgSrddH5WClO+gHH9up0rKB9fgQK6qepCChVo9De1A+DGP9Uly5PeGxN3VFZeilB0Ol1npBIslS7NoJ8mS9TtXI2v1JmngBeb5K9YRExqnoV4XV14EGqZ2vf6lMTm0f95GL7kacJM51q+b6PuogYZda4ZRsYLNkgyYCTLuFyDi2qGzlRqjcMlqQzf4w8a7X3D3IWcNspiMHaB60KakUkugobrKwll06h0J9vL/fMHwV6IYwZ39wcNrbtEqTB+PyPT07dyVZ5CZrFKDj2JGSEPpduBbA7mlWtLdVa63oVcIgEq4/gNPzU6jZ1NSszrkRjjUb4O8Eu9VImvt/KDCqIU4xp70FLE4Rwql4V122xKaPLI8HNzlvUUE=
    on:
      tags: true
      node_js: '0.12'
      branch: master
